### ISSUE TITLE
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'

### ISSUE THREAD

**Issue by cbrandys** [cisagov/check-your-pulse#2]
Receiving this output when trying to run. 

Traceback (most recent call last):
  File "app.py", line 380, in <module>
    _summary(
  File "app.py", line 336, in _summary
    conn_list = sorted(conn_list, key=lambda x: x[0])
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'

**Comment by DeemOnSecurity** [comment]
Thank you for raising this issue! We are currently trying to resolve :)

**Comment by DeemOnSecurity** [comment]
@cbrandys would you mind cloning the branch: issue2 and let us know if it resolves this?

**Comment by cbrandys** [comment]
Thanks for the quick response. This is the error I am receiving now.

Traceback (most recent call last):
  File "app.py", line 382, in <module>
    _summary(
  File "app.py", line 336, in _summary
    conn_list = sorted(
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'

**Comment by DeemOnSecurity** [comment]
Hmm, I pushed another potential fix if you want to clone again and try it out. 

If this still isn't working, would you be able to get me some form of sanitized logs? This appears to have something to do with the Connection._date_time() not parsing the time in your logs properly.

**Comment by cbrandys** [comment]
Ok. tried it with a different appliances logs and it worked. Thank you for the help!

**Comment by DeemOnSecurity** [comment]
> Ok. tried it with a different appliances logs and it worked. Thank you for the help!

Glad I could help! You couldn't get it to work on the appliance you started with in the beginning? Is there noticeable differences in the log formats? 

One thing we noticed at the beginning of this project is that different versions of pulse secure have some different log formats which broke the initial implementation.
