### ISSUE TITLE
Error parsing logs

### ISSUE THREAD

**Issue by rzwingman** [cisagov/check-your-pulse#8]
Running into an error while running script with the following output:

Paste the results here:
[Done] Parsing ['./log.events']
[Done] Parsing ['./log.access']
Traceback (most recent call last):
  File "./app.py", line 408, in <module>
    unauthenticated_logging,
  File "./app.py", line 343, in _summary
    conn_list, key=lambda x: x[0] if x else datetime.datetime.now()
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
cr-130rzwingman@Z-MBP-16 check-your-pulse % python3 ./app.py -r
usage: app.py [-h] [-r RAW] [-c CSV] [-j JSON] [-p PATH] [-n NUMEVENTS]
app.py: error: argument -r/--raw: expected one argument
```bash

```

**Comment by DeemOnSecurity** [comment]
Good evening,

 It appears you are getting this result because -r/--raw expects an argument for it to output to. Try app.py -r log.raw.

Will

**Comment by rzwingman** [comment]
Hello Will,

Thank you for the reply. It seems that I get the same error:

Z-MBP-16 check-your-pulse % python3 ./app.py -r log.raw
[Done] Parsing ['./log.events']
[Done] Parsing ['./log.access']
Traceback (most recent call last):
  File "./app.py", line 408, in <module>
    unauthenticated_logging,
  File "./app.py", line 343, in _summary
    conn_list, key=lambda x: x[0] if x else datetime.datetime.now()
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
 
(which I also get with no arguments)

Z-MBP-16 check-your-pulse % python3 ./app.py
[Done] Parsing ['./log.events']
[Done] Parsing ['./log.access']
Traceback (most recent call last):
  File "./app.py", line 408, in <module>
    unauthenticated_logging,
  File "./app.py", line 343, in _summary
    conn_list, key=lambda x: x[0] if x else datetime.datetime.now()
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'

check-your-pulse % ls -lh
total 392856
-rw-r--r--  1 cr-130  staff   4.6K Aug 17 14:33 CONTRIBUTING.md
-rw-r--r--  1 cr-130  staff   6.4K Aug 17 14:33 LICENSE
-rw-r--r--  1 cr-130  staff   5.9K Aug 17 14:33 README.md
-rw-r--r--  1 cr-130  staff    16K Aug 17 14:33 app.py
-rw-r--r--@ 1 cr-130  staff   114M Aug 17 14:12 log.access
-rw-r--r--@ 1 cr-130  staff    78M Aug 17 14:12 log.events
-rw-r--r--  1 cr-130  staff    11B Aug 17 14:33 requirements-test.txt
-rw-r--r--  1 cr-130  staff     0B Aug 17 14:33 requirements.txt
-rw-r--r--  1 cr-130  staff   2.5K Aug 17 14:33 setup.py
drwxr-xr-x  5 cr-130  staff   160B Aug 17 14:36 src

Ray

**Comment by DeemOnSecurity** [comment]
I have pushed to branch "issue8", which should hopefully resolve this error!

**Comment by rzwingman** [comment]
Thank you! That worked for RAW output.
